`timescale 1ns / 1ps
//`define BEHAVIORAL_SIM // <--- COMMENT OUT for post-synthesis / implementation

//======================================================================
//  tb_accelerator_TOP.v
//  Multi-image self-checking testbench for the CNN accelerator.
//
//  Reads configuration + test vectors from files generated by
//  train_and_gen_model_init_files_V3.py:
//
//    test_images_uart/test_config.hex       - [num_images, bytes_per_image,
//                                              fc_base, num_classes]
//    test_images_uart/all_uart_bytes.hex    - all UART streams concatenated
//    test_images_uart/expected_classes.hex  - FP-model prediction per image
//    test_images_uart/true_labels.hex       - MNIST ground-truth label
//    bram_instructions_init.hex             - instruction BRAM init
//    bram_weights_init.hex                  - weight BRAM init
//
//  Test flow:
//    Phase 1  - Spot-check BRAM initialisation (behavioral only)
//    Phase 2  - For each image:
//                 a. Reset DUT
//                 b. Transmit image via UART
//                 c. Wait for LED_OPS_DONE
//                 d. Compare HW result to expected class
//    Phase 3  - Summary: per-image log, HW-correctness count, model accuracy
//======================================================================

// =====================================================================
//  Behavioural Primitives (for behavioral sim only)
// =====================================================================
module BUFGCE (output O, input CE, input I);
    assign O = I & CE;
endmodule

module bram_instructions (
    input clka, input ena, input wea,
    input [9:0] addra, input [63:0] dina, output reg [63:0] douta
);
    reg [63:0] mem [0:1023];
    reg [63:0] pipe;
    integer init_i;
    initial begin
        for (init_i = 0; init_i < 1024; init_i = init_i + 1)
            mem[init_i] = 64'h0;
        $readmemh("bram_instructions_init.hex", mem);
    end
    always @(posedge clka) begin
        if (ena) begin
            if (wea) mem[addra] <= dina;
            pipe <= mem[addra];
        end
        douta <= pipe;
    end
endmodule

module bram_weights (
    input clka, input ena, input wea,
    input [13:0] addra, input [15:0] dina, output reg [15:0] douta
);
    reg [15:0] mem [0:16383];
    reg [15:0] pipe;
    integer init_i;
    initial begin
        for (init_i = 0; init_i < 16384; init_i = init_i + 1)
            mem[init_i] = 16'h0;
        $readmemh("bram_weights_init.hex", mem);
    end
    always @(posedge clka) begin
        if (ena) begin
            if (wea) mem[addra] <= dina;
            pipe <= mem[addra];
        end
        douta <= pipe;
    end
endmodule

module bram_activations (
    input clka,
    input ena, input wea, input [13:0] addra, input [127:0] dina,
    input clkb, input enb, input [13:0] addrb, output reg [127:0] doutb
);
    reg [127:0] mem [0:16383];
    reg [127:0] pipe_b;
    integer init_i;
    initial begin
        for (init_i = 0; init_i < 16384; init_i = init_i + 1)
            mem[init_i] = 128'h0;
    end
    always @(posedge clka) begin
        if (ena && wea) mem[addra] <= dina;
    end
    always @(posedge clkb) begin
        if (enb) pipe_b <= mem[addrb];
        doutb <= pipe_b;
    end
endmodule

// =====================================================================
//  Testbench
// =====================================================================
module tb_accelerator_TOP;

    // -----------------------------------------------------------------
    //  Timing & sizing parameters
    // -----------------------------------------------------------------
    localparam CLK_PERIOD       = 20;                       // 100 MHz
    localparam CLOCK_FREQ       = 100_000_000;
    localparam SIM_BAUD_RATE    = 2_000_000;                // 2 Mbaud for sim
    localparam CLKS_PER_BIT     = CLOCK_FREQ / SIM_BAUD_RATE;
    localparam BIT_PERIOD       = CLKS_PER_BIT * CLK_PERIOD;
    localparam TIMEOUT_CYCLES   = 200_000_000;

    localparam MAX_IMAGES       = 128;
    localparam MAX_BYTES_PER_IMG= 4096;
    localparam MAX_TOTAL_BYTES  = MAX_IMAGES * MAX_BYTES_PER_IMG;  // 524 288

    // -----------------------------------------------------------------
    //  DUT signals
    // -----------------------------------------------------------------
    reg         clk;
    reg         reset;
    reg         uart_rx_pin;
    wire        uart_tx_pin;
    //wire [6:0]  seg7_seg;
    //wire [3:0]  seg7_anode;
    wire        led_busy, led_done, led_datarx, led_idle;
    wire [3:0]  cnn_detected_digit;

    // -----------------------------------------------------------------
    //  DUT
    // -----------------------------------------------------------------
    accelerator_TOP uut (
        .CLK           (clk),
        .RESET         (reset),
        .UART_RX_ASYNC (uart_rx_pin),
        .UART_TX       (uart_tx_pin),
        //.SEG7_SEG      (seg7_seg),
        //.SEG7_ANODE    (seg7_anode),
        .LED_OPS_BUSY  (led_busy),
        .LED_OPS_DONE  (led_done),
        .LED_OPS_DATARX(led_datarx),
        .LED_IDLE      (led_idle),
        .CNN_DETECTED_DIGIT(cnn_detected_digit)
    );

    `ifdef BEHAVIORAL_SIM
        defparam uut.u_host_if.BAUD_RATE = SIM_BAUD_RATE;
    `endif

    // -----------------------------------------------------------------
    //  Clock
    // -----------------------------------------------------------------
    initial clk = 0;
    always #(CLK_PERIOD / 2) clk = ~clk;

    // -----------------------------------------------------------------
    //  Data arrays
    // -----------------------------------------------------------------
    reg [31:0] test_config     [0:3];
    reg [ 7:0] all_uart_data   [0:MAX_TOTAL_BYTES-1];
    reg [15:0] expected_classes [0:MAX_IMAGES-1];
    reg [15:0] true_labels     [0:MAX_IMAGES-1];
    reg [63:0] ref_instructions[0:1023];
    reg [15:0] ref_weights     [0:16383];

    // Runtime config (populated from test_config.hex)
    integer num_test_images;
    integer bytes_per_image;
    integer fc_out_base;
    integer num_classes;

    // Counters
    integer errors;              // HW != expected  (hardware bugs)
    integer hw_pass_count;       // HW == expected  (hardware correct)
    integer model_correct_count; // HW == true label (model accurate)
    integer i;

    // -----------------------------------------------------------------
    //  UART transmit task  (LSB-first, 1 start, 8 data, 1 stop)
    // -----------------------------------------------------------------
    task uart_send_byte;
        input [7:0] data;
        integer b;
        begin
            uart_rx_pin = 1'b0;
            #(BIT_PERIOD);
            for (b = 0; b < 8; b = b + 1) begin
                uart_rx_pin = data[b];
                #(BIT_PERIOD);
            end
            uart_rx_pin = 1'b1;
            #(BIT_PERIOD);
        end
    endtask

    // -----------------------------------------------------------------
    //  7-Segment decoder (for black-box / post-synth testing)
    // -----------------------------------------------------------------
    function [15:0] decode_7seg;
        input [6:0] seg_val;
        begin
            case (seg_val)
                7'b1000000: decode_7seg = 16'd0;
                7'b1111001: decode_7seg = 16'd1;
                7'b0100100: decode_7seg = 16'd2;
                7'b0110000: decode_7seg = 16'd3;
                7'b0011001: decode_7seg = 16'd4;
                7'b0010010: decode_7seg = 16'd5;
                7'b0000010: decode_7seg = 16'd6;
                7'b1111000: decode_7seg = 16'd7;
                7'b0000000: decode_7seg = 16'd8;
                7'b0010000: decode_7seg = 16'd9;
                default:    decode_7seg = 16'hFFFF;
            endcase
        end
    endfunction

    // -----------------------------------------------------------------
    //  LED transition monitor (background process)
    // -----------------------------------------------------------------
    reg led_datarx_prev, led_busy_prev, led_done_prev;

    always @(posedge clk) begin
        if (!reset) begin
            if ( led_datarx && !led_datarx_prev)
                $display("[%0t] LED: Data-RX ON  - receiving image", $time);
            if (!led_datarx &&  led_datarx_prev)
                $display("[%0t] LED: Data-RX OFF", $time);
            if ( led_busy && !led_busy_prev)
                $display("[%0t] LED: CNN_BUSY ON  - inference running", $time);
            if (!led_busy &&  led_busy_prev)
                $display("[%0t] LED: CNN_BUSY OFF", $time);
            if ( led_done && !led_done_prev)
                $display("[%0t] LED: OPS_DONE ON  - inference complete", $time);
        end
        led_datarx_prev <= led_datarx;
        led_busy_prev   <= led_busy;
        led_done_prev   <= led_done;
    end

    // -----------------------------------------------------------------
    //  Main test sequence
    // -----------------------------------------------------------------
    reg [15:0] hw_result;

    initial begin

        // ============================================================
        //  0.  Load all data files
        // ============================================================
        errors              = 0;
        hw_pass_count       = 0;
        model_correct_count = 0;
        uart_rx_pin         = 1'b1;
        reset               = 1'b1;

        for (i = 0; i < 4;              i = i + 1) test_config[i]      = 32'h0;
        for (i = 0; i < MAX_TOTAL_BYTES; i = i + 1) all_uart_data[i]   = 8'h0;
        for (i = 0; i < MAX_IMAGES;      i = i + 1) expected_classes[i] = 16'h0;
        for (i = 0; i < MAX_IMAGES;      i = i + 1) true_labels[i]     = 16'h0;
        for (i = 0; i < 1024;            i = i + 1) ref_instructions[i] = 64'h0;
        for (i = 0; i < 16384;           i = i + 1) ref_weights[i]      = 16'h0;

        $readmemh("test_config.hex",      test_config);
        $readmemh("all_uart_bytes.hex",   all_uart_data);
        $readmemh("expected_classes.hex", expected_classes);
        $readmemh("true_labels.hex",      true_labels);
        $readmemh("bram_instructions_init.hex",            ref_instructions);
        $readmemh("bram_weights_init.hex",                 ref_weights);

        num_test_images = test_config[0];
        bytes_per_image = test_config[1];
        fc_out_base     = test_config[2];
        num_classes     = test_config[3];

        $display("==============================================================");
        $display("  CNN Accelerator - Multi-Image Self-Checking Testbench");
        $display("==============================================================");
        $display("  Clock         : %0d MHz", CLOCK_FREQ / 1_000_000);
        $display("  Sim baud      : %0d", SIM_BAUD_RATE);
        $display("  Test images   : %0d", num_test_images);
        $display("  Bytes / image : %0d", bytes_per_image);
        $display("  FC base addr  : %0d", fc_out_base);
        $display("  Num classes   : %0d", num_classes);
        $display("==============================================================\n");

        // ============================================================
        //  Initial reset
        // ============================================================
        #(CLK_PERIOD * 20);
        reset = 1'b0;
        #(CLK_PERIOD * 10);

        // ============================================================
        //  PHASE 1: BRAM initialisation check (behavioral only)
        // ============================================================
        `ifdef BEHAVIORAL_SIM
            $display("[PHASE 1] Verifying BRAM initialisation ...");
            begin : check_instr
                integer addr;
                reg [63:0] got, exp;
                for (addr = 0; addr < 15; addr = addr + 1) begin
                    got = uut.u_inst_mem.bram_instructions_0.mem[addr];
                    exp = ref_instructions[addr];
                    if (got !== exp) begin
                        $display("  [FAIL] Instr[%0d] got=%016H  exp=%016H",
                                 addr, got, exp);
                        errors = errors + 1;
                    end
                end
            end
            begin : check_wgt
                integer addr;
                reg [15:0] got, exp;
                for (addr = 0; addr < 20; addr = addr + 1) begin
                    got = uut.u_wgt_mem.bram_weights_0.mem[addr];
                    exp = ref_weights[addr];
                    if (got !== exp) begin
                        $display("  [FAIL] Wgt[%0d] got=%04H  exp=%04H",
                                 addr, got, exp);
                        errors = errors + 1;
                    end
                end
            end
            if (errors == 0)
                $display("  [PASS] BRAM initialisation OK.\n");
            else
                $display("  [WARN] %0d BRAM mismatches.\n", errors);
        `else
            $display("[PHASE 1] Skipping deep BRAM checks (post-synth mode).\n");
        `endif

        // ============================================================
        //  PHASE 2: Multi-image test loop
        // ============================================================
        $display("[PHASE 2] Running %0d test images ...\n", num_test_images);

        begin : image_loop
            integer img_idx;
            integer byte_idx;
            integer base_offset;

            for (img_idx = 0; img_idx < num_test_images;
                 img_idx = img_idx + 1)
            begin

                // ---- 2a. Reset DUT between images ----
                if (img_idx > 0) begin
                    reset = 1'b1;
                    #(CLK_PERIOD * 10);
                    reset = 1'b0;
                    #(CLK_PERIOD * 10);
                end

                $display("  --- Image %0d / %0d  (label=%0d, fp_expected=%0d) ---",
                         img_idx, num_test_images,
                         true_labels[img_idx], expected_classes[img_idx]);

                // ---- 2b. Transmit UART bytes ----
                base_offset = img_idx * bytes_per_image;

                for (byte_idx = 0; byte_idx < bytes_per_image;
                     byte_idx = byte_idx + 1) begin
                    uart_send_byte(all_uart_data[base_offset + byte_idx]);
                end

                // ---- 2c. Wait for inference ----
                begin : wait_inference
                    integer cyc;
                    for (cyc = 0; cyc < TIMEOUT_CYCLES; cyc = cyc + 1) begin
                        @(posedge clk);
                        if (led_done) begin
                            $display("      Inference done in %0d cycles.", cyc);
                            disable wait_inference;
                        end
                    end
                    $display("      [FAIL] TIMEOUT after %0d cycles!",
                             TIMEOUT_CYCLES);
                    errors = errors + 1;
                end

                // Let seg7_driver latch the result
                #(CLK_PERIOD * 20);

                // ---- 2d. Read result and compare ----
                `ifdef BEHAVIORAL_SIM
                    hw_result = uut.u_seg7.CNN_RESULT;
                `else
                    hw_result = {12'd0, cnn_detected_digit};
                `endif

                // ---- Functional check: HW == FP reference ----
                if (hw_result == expected_classes[img_idx]) begin
                    hw_pass_count = hw_pass_count + 1;
                    if (hw_result == true_labels[img_idx])
                        $display("      HW=%0d  exp=%0d  label=%0d  HW_CHECK: PASS   MODEL: CORRECT",
                                 hw_result, expected_classes[img_idx],
                                 true_labels[img_idx]);
                    else
                        $display("      HW=%0d  exp=%0d  label=%0d  HW_CHECK: PASS   MODEL: WRONG",
                                 hw_result, expected_classes[img_idx],
                                 true_labels[img_idx]);
                end else begin
                    errors = errors + 1;
                    $display("      HW=%0d  exp=%0d  label=%0d  HW_CHECK: *** FAIL ***",
                             hw_result, expected_classes[img_idx],
                             true_labels[img_idx]);
                end

                // Model accuracy
                if (hw_result == true_labels[img_idx])
                    model_correct_count = model_correct_count + 1;

                // ---- Optional logit dump (behavioral only) ----
                `ifdef BEHAVIORAL_SIM
                    begin : dump_logits
                        integer a;
                        reg signed [15:0] logit;
                        $write("      Logits:");
                        for (a = 0; a < num_classes; a = a + 1) begin
                            logit = uut.u_act_mem.bram_activations_0.mem[fc_out_base + a][15:0];
                            $write(" [%0d]=%0d", a, logit);
                        end
                        $write("\n");
                    end
                `endif

                $display("");
            end
        end

        // ============================================================
        //  PHASE 3: Summary
        // ============================================================
        $display("==============================================================");
        $display("  MULTI-IMAGE TEST SUMMARY");
        $display("==============================================================");
        $display("  Total images tested  : %0d", num_test_images);
        $display("");
        $display("  HW Correctness (HW == FP reference)");
        $display("    PASSED : %0d / %0d", hw_pass_count, num_test_images);
        if (errors > 0)
            $display("    FAILED : %0d  (indicates hardware bugs)", errors);
        $display("");
        $display("  Model Accuracy (HW output == true MNIST label)");
        $display("    CORRECT: %0d / %0d", model_correct_count, num_test_images);
        $display("==============================================================");

        if (errors == 0)
            $display("  VERDICT:  *** ALL HARDWARE CHECKS PASSED ***");
        else
            $display("  VERDICT:  *** FAILED - %0d hardware error(s) ***", errors);

        $display("==============================================================\n");

        #(CLK_PERIOD * 1000);
        $finish;
    end

    // -----------------------------------------------------------------
    //  VCD dump (optional - comment out for large image sets)
    // -----------------------------------------------------------------
    // initial begin
    //     $dumpfile("tb_accelerator_TOP.vcd");
    //     $dumpvars(0, tb_accelerator_TOP);
    // end

endmodule