create_clock -period 10.000 -name CLK -waveform {0.000 5.000} [get_ports CLK]

set_property IOSTANDARD LVCMOS18 [get_ports CLK]
set_property IOSTANDARD LVCMOS18 [get_ports {SEG7_ANODE[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SEG7_ANODE[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SEG7_ANODE[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SEG7_ANODE[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SEG7_SEG[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SEG7_SEG[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SEG7_SEG[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SEG7_SEG[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SEG7_SEG[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SEG7_SEG[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SEG7_SEG[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports LED_IDLE]
set_property IOSTANDARD LVCMOS18 [get_ports LED_OPS_BUSY]
set_property IOSTANDARD LVCMOS18 [get_ports LED_OPS_DATARX]
set_property IOSTANDARD LVCMOS18 [get_ports LED_OPS_DONE]
set_property IOSTANDARD LVCMOS18 [get_ports RESET]
set_property IOSTANDARD LVCMOS18 [get_ports UART_RX_ASYNC]
set_property IOSTANDARD LVCMOS18 [get_ports UART_TX]
