`timescale 1ns / 1ps

module ops_maxpool(
    // clk, reset, module_en:
    input   CLK_IN,
    input   RESET,  // active HIGH reset
    input MODULE_EN,    // gates clk, active HIGH
    
    // control signals:

    input EXT_START_OF_COMPUTE,
    output reg EXT_END_OF_COMPUTE,

    // input activation:
    input [13:0] IN_FMAP_BASEADDR,
    input [9:0] IN_FMAP_DIM_W,
    input [9:0] IN_FMAP_DIM_H,
    input [9:0] IN_FMAP_DIM_C,

    // output activation:
    input [13:0] OUT_FMAP_BASEADDR,
    input [9:0] OUT_FMAP_DIM_W,
    input [9:0] OUT_FMAP_DIM_H,
    input [9:0] OUT_FMAP_DIM_C,

    // pooling parameters:
    input [7:0] POOL_KERNEL_SIZE,

    // activations BRAM interface:
    // port a:
    output reg BRAM_ena,
    output reg BRAM_wea,
    output reg [13:0] BRAM_addra,
    output reg [15:0] BRAM_dina,
    // port b:
    output reg BRAM_enb,
    output reg [13:0] BRAM_addrb,
    input [15:0] BRAM_doutb
    );
    
    /*
        MODULE DESCRIPTION:

        - Max Pooling operation for 3D feature maps.
        - Supports variable kernel sizes (e.g., 2x2, 3x3).
        - Stride is equal to kernel size (non-overlapping pooling).
        - A window is [POOL_KERNEL_SIZE x POOL_KERNEL_SIZE].

        - The module contains an FSM and an Address Generation Unit (AGU). 
        -- The states of the FSM are as follows:
        ---- IDLE:  Initializes variables, including win_max. Stays in this state until EXT_START_OF_COMPUTE is asserted.
        ---- FILL:  Fills pipeline (BRAM has 2 cycle latency: CLK1: set BRAM_en, BRAM_addrb, CLK2: read BRAM_doutb )
        ---- COMPUTE:   Reads BRAM data line, updates BRAM's address line (for next clock)
                        Keeps on comparing currently read pixel with win_max. 
                        At the end of the window, writes win_max to output activation address.
                        The address for the current pixel is updated by the combinational AGU.
                        The FSM stays in this state until the entire fmap is iterated over (IN_FMAP_DIM_W x IN_FMAP_DIM_H x IN_FMAP_DIM_C)
        ---- FLUSH: Reads the final pixel without setting a new address onto BRAM's address lines. Flushes the pipeline.
        ---- DONE:  Asserts EXT_END_OF_COMPUTE signal to the controller

    */

    // clock gating:

    wire CLK;

    // Using a Xilinx BUFGCE primitive for clock gating
    BUFGCE u_clock_gating_buffer (
        .O(CLK),   // Gated clock output
        .CE(MODULE_EN),    // Clock enable input (synchronous to clk)
        .I(CLK_IN)     // Primary clock input
    );

    //////////////// FSM CODE BEGIN ////////////////

    // registers:
    //state:
    reg [2:0] state_curr;
    reg [2:0] state_next;
    // pointers (_next: assigned by AGU using normal ones and used by FSM, normal ones: modified and assigned by FSM):
    reg [9:0] h_in, h_in_next;
    reg [9:0] w_in, w_in_next;
    reg [9:0] c_in, c_in_next;
    reg [9:0] h_out, h_out_next;
    reg [9:0] w_out, w_out_next;
    reg [9:0] c_out, c_out_next;
    reg [13:0] win_start_addr, win_start_addr_next;
    reg [13:0] win_row_start_addr, win_row_start_addr_next;
    // pipeline counters (max 3 wait states):
    reg [2:0] pipe_fill_ctr, pipe_flush_ctr;
    parameter NUM_WAIT_STATES_BRAM = 3;     // 3 because sequence is: clk1: BRAM_addrb generated by AGU; clk2: BRAM_addrb latched by BRAM; clk3: BRAM_doutb available
    // local storage registers:
    reg [15:0] win_max;
    // control signals:
    reg fmap_compute_almost_done;
    reg win_complete_flag;
    reg [NUM_WAIT_STATES_BRAM-1:0] win_done_sr; // shift register to delay win_complete_flag by wait states required by BRAM
    reg [13:0] out_write_addr;

    // offsets:
    reg [13:0] inside_fmap_channel_offset;
    reg [13:0] row_jump_offset;
    reg [13:0] win_base_addr, win_base_addr_next;
    reg [13:0] fmap_row_start_addr, fmap_row_start_addr_next;
    reg [13:0] channel_start_addr, channel_start_addr_next;


    // define states:
    localparam IDLE = 0;
    localparam FILL = 1;
    localparam COMPUTE = 2;
    localparam FLUSH = 3;
    localparam DONE = 4;

    // state transition logic:
    always @(*) begin
        
        // Default
        state_next = state_curr;

        case(state_curr)
            IDLE: begin

                if (EXT_START_OF_COMPUTE)
                    state_next = FILL;
                else
                    state_next = IDLE;
            end

            FILL: begin
                
                if (pipe_fill_ctr == 0)
                    state_next = COMPUTE;
                else begin
                    state_next = FILL;
                end
            end

            COMPUTE: begin
                
                if (fmap_compute_almost_done)
                    state_next = FLUSH;
                else
                    state_next = COMPUTE;
            end

            FLUSH: begin
                
                if (pipe_flush_ctr == 0)
                    state_next = DONE;
                else
                    state_next = FLUSH;
            end

            DONE: begin
                state_next = IDLE;
            end

            default: state_next = IDLE;
        endcase
    end 

    // state transition and clocked output assignment:
    always @(posedge CLK) begin
        if (RESET) begin
            state_curr <= IDLE;
            EXT_END_OF_COMPUTE <= 0;
            BRAM_enb <= 0;
            BRAM_ena <= 0;
            BRAM_wea <= 0;
            win_max <= 0;
            BRAM_addrb         <= 0;
            BRAM_addra         <= 0;   
            BRAM_dina          <= 0;   
        end else begin
            state_curr <= state_next;
            case(state_curr)
                IDLE: begin
                    // initialize pointers:
                    h_in <= 0; w_in <= 0; c_in <= 0; h_out <= 0; w_out <= 0; c_out <= 0;
                    win_start_addr <= IN_FMAP_BASEADDR; 
                    win_row_start_addr <= IN_FMAP_BASEADDR;
                    win_base_addr <= IN_FMAP_BASEADDR;
                    fmap_row_start_addr <= IN_FMAP_BASEADDR;
                    channel_start_addr <= IN_FMAP_BASEADDR;

                    // initialize offsets:
                    inside_fmap_channel_offset <= IN_FMAP_DIM_W * IN_FMAP_DIM_H;
                    row_jump_offset <= POOL_KERNEL_SIZE * IN_FMAP_DIM_W;

                    // initialize pipeline ctrs:
                    pipe_fill_ctr <= NUM_WAIT_STATES_BRAM - 1; 
                    pipe_flush_ctr <= NUM_WAIT_STATES_BRAM - 1;

                    // Reset control signals
                    EXT_END_OF_COMPUTE <= 0;
                    BRAM_enb <= 0;
                    BRAM_wea <= 0;
                    
                    win_done_sr <= 0;
                    out_write_addr <= OUT_FMAP_BASEADDR;    
                    
                    win_max <= 0;
                end

                FILL: begin
                    h_in               <= h_in_next;
                    w_in               <= w_in_next;
                    h_out              <= h_out_next; 
                    w_out              <= w_out_next; 
                    c_in               <= c_in_next;  
                    c_out              <= c_out_next; 
                    
                    win_start_addr     <= win_start_addr_next;
                    win_row_start_addr <= win_row_start_addr_next;
                    pipe_fill_ctr      <= pipe_fill_ctr - 1;

                    BRAM_enb   <= 1;
                    BRAM_addrb <= win_start_addr;

                    win_base_addr        <= win_base_addr_next;
                    fmap_row_start_addr  <= fmap_row_start_addr_next;
                    channel_start_addr   <= channel_start_addr_next;

                    win_done_sr <= {win_done_sr[NUM_WAIT_STATES_BRAM-2:0], win_complete_flag};
                end

                COMPUTE: begin
                    h_in               <= h_in_next;
                    w_in               <= w_in_next;
                    h_out              <= h_out_next;
                    w_out              <= w_out_next;
                    c_in               <= c_in_next;
                    c_out              <= c_out_next; 
                    
                    win_start_addr     <= win_start_addr_next;
                    win_row_start_addr <= win_row_start_addr_next;

                    BRAM_enb   <= 1;
                    BRAM_addrb <= win_start_addr;
                    
                    win_base_addr      <= win_base_addr_next;
                    fmap_row_start_addr<= fmap_row_start_addr_next;
                    channel_start_addr <= channel_start_addr_next;

                    // output write, based on read latency:
                    // 1. Shift the flag
                    win_done_sr <= {win_done_sr[NUM_WAIT_STATES_BRAM-2:0], win_complete_flag};

                    // 2. Write-back triggered by the MSB of the shift register
                    if (win_done_sr[NUM_WAIT_STATES_BRAM-1]) begin
                        BRAM_ena   <= 1;
                        BRAM_wea   <= 1;
                        BRAM_addra <= out_write_addr;
                        BRAM_dina  <= (BRAM_doutb > win_max) ? BRAM_doutb : win_max;
                        
                        out_write_addr <= out_write_addr + 1; // increment by 1
                        win_max <= 0; // Reset for next window
                    end else begin
                        BRAM_ena <= 0;
                        BRAM_wea <= 0;
                        win_max <= (BRAM_doutb > win_max) ? BRAM_doutb : win_max;
                    end
                end

                FLUSH: begin
                    BRAM_enb <= 1;
                    pipe_flush_ctr <= pipe_flush_ctr - 1;

                    // Feed zeros into the pipeline to drain it
                    win_done_sr <= {win_done_sr[NUM_WAIT_STATES_BRAM-2:0], 1'b0};

                    // Same write logic as COMPUTE to catch the final window
                    if (win_done_sr[NUM_WAIT_STATES_BRAM-1]) begin
                        BRAM_ena   <= 1;
                        BRAM_wea   <= 1;
                        BRAM_addra <= out_write_addr;
                        BRAM_dina  <= (BRAM_doutb > win_max) ? BRAM_doutb : win_max;
                        
                        out_write_addr <= out_write_addr + 1;
                        win_max <= 0;
                    end else begin
                        BRAM_ena <= 0;
                        BRAM_wea <= 0;
                        win_max <= (BRAM_doutb > win_max) ? BRAM_doutb : win_max;
                    end
                end

                DONE: begin
                    EXT_END_OF_COMPUTE <= 1;
                end

            endcase
        end
    end

    //////////////// FSM CODE END   ////////////////

/*
    //////////////// DEBUG / PRINT STATE ///////////

    always @(state_curr) begin
        $write("[%0t ns] ops_maxpool State Transition: ", $time);
        case(state_curr)
            IDLE:    $display("IDLE");
            FILL:    $display("FILL");
            COMPUTE: $display("COMPUTE");
            FLUSH:   $display("FLUSH");
            DONE:    $display("DONE");
            default: $display("UNKNOWN STATE");
        endcase
    end
    
    ////////////////////////////////////////////////
*/

//////////////// AGU CODE BEGIN ////////////////

    always @(*) begin
        
        
        // Defaults to prevent latches:
        h_in_next                = h_in;
        w_in_next                = w_in;
        h_out_next               = h_out;
        w_out_next               = w_out;
        c_in_next                = c_in;
        c_out_next               = c_out;
        win_start_addr_next      = win_start_addr;
        win_row_start_addr_next  = win_row_start_addr;
        win_complete_flag        = 1'b0;
        fmap_compute_almost_done = 1'b0;
        win_base_addr_next       = win_base_addr;
        fmap_row_start_addr_next = fmap_row_start_addr;
        channel_start_addr_next  = channel_start_addr;

        // Only advance pointers if FSM is actively running the pipeline
        if (state_curr == FILL || state_curr == COMPUTE) begin
            
            if (w_in == POOL_KERNEL_SIZE - 1) begin
                w_in_next = 0; 
                
                if (h_in == POOL_KERNEL_SIZE - 1) begin
                    h_in_next = 0; 
                    win_complete_flag = 1'b1;
                    
                    // FMAP SLIDING LOGIC 
                    if (w_out == OUT_FMAP_DIM_W - 1) begin
                        w_out_next = 0; 
                        
                        if (h_out == OUT_FMAP_DIM_H - 1) begin
                            h_out_next = 0; 
                            
                            if (c_out == OUT_FMAP_DIM_C - 1) begin
                                fmap_compute_almost_done = 1'b1; 
                            end else begin
                                // Jump to Next Channel
                                c_out_next = c_out + 1;
                                c_in_next  = c_in + 1;
                                
                                // Advance the channel anchor
                                channel_start_addr_next  = channel_start_addr + inside_fmap_channel_offset;
                                
                                // Reset all other anchors to the new channel start
                                fmap_row_start_addr_next = channel_start_addr_next;
                                win_base_addr_next       = channel_start_addr_next;
                                win_row_start_addr_next  = channel_start_addr_next;
                                win_start_addr_next      = channel_start_addr_next;
                            end
                        end else begin
                            // Jump to Next Row of Windows
                            h_out_next = h_out + 1;
                            
                            // Advance the FMAP row anchor (using the offset calculated in IDLE)
                            fmap_row_start_addr_next = fmap_row_start_addr + row_jump_offset;
                            
                            // Reset window anchors to the start of this new row
                            win_base_addr_next       = fmap_row_start_addr_next;
                            win_row_start_addr_next  = fmap_row_start_addr_next;
                            win_start_addr_next      = fmap_row_start_addr_next;
                        end
                    end else begin
                        // Slide Window Right
                        w_out_next = w_out + 1;
                        
                        // Advance the window anchor right by the pool size
                        win_base_addr_next       = win_base_addr + POOL_KERNEL_SIZE;
                        
                        // Reset the reading pointers to this new window anchor
                        win_row_start_addr_next  = win_base_addr_next;
                        win_start_addr_next      = win_base_addr_next;
                    end
                end else begin
                    // Move down 1 row INSIDE the current window
                    h_in_next = h_in + 1;
                    win_row_start_addr_next = win_row_start_addr + IN_FMAP_DIM_W;
                    win_start_addr_next     = win_row_start_addr + IN_FMAP_DIM_W;
                end
            end else begin
                // Move right 1 pixel INSIDE the current window
                w_in_next = w_in + 1;
                win_start_addr_next = win_start_addr + 1;
            end
        end
    end
    //////////////// AGU CODE END   ////////////////

endmodule